version: 2.1

           
jobs:
  build-frontend:
    
  
  build-backend:
    
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run test

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend